# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtfITBq8VttSAkkN8nfVTNAgsgjaZscn

NumPy - Numerical Python
"""

import numpy as np

"""List vs Numpy - Time comparison"""

from time import process_time
python_list=[i for i in range(1000000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array=np_array+5
end_time=process_time()
print(end_time-start_time)

"""NumPy Arrays"""

list1=[1,2,3,4,5]
print(list1)
print(type(list1))

np_array=np.array([1,2,3,4,5])
print(np_array)
(type(np_array))

# creating 1 Dim Np Array
np_array1=np.array([1,2,3,4,5])
print(np_array1)
np_array1.shape

np_array2=np.array([(1,2,3),(3,4,5)])
print(np_array2)
np_array2.shape

#create array with zeros
np_array3=np.zeros((2,3))
print(np_array3)

#create array with ones
np_array4=np.ones((3,3))
print(np_array4)

# create a array with particular value
np_array5=np.full((3,3),5)
print(np_array5)

# create a array with identical
np_array6=np.eye(3)
print(np_array6)

# create a array with random
np_array7=np.random.random((3,3))
print(np_array7)

c= np.random.randint(5,12,(3,3))
print(c)

"""**Mathematical Operations**"""

list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

#np array runs element wise operation is available
a=np.random.randint(3,9,(3,3))
b=np.random.randint(3,9,(3,3))
print(a)
print(b)
print(a+b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

"""**Array Manipulations**"""

array=np.random.randint(1,10,(3,3))
print(array)
print(array.shape)